---
- name: Pull latest Postgres image and recreate container  
  community.docker.docker_compose_v2:    
    project_src: "{{ deployment_dir }}"
    files:
      - docker-compose.yml
    services:
      - "postgres"
    pull: always
    recreate: always
  environment:
    DOCKER_CONFIG: "/home/{{ ansible_user }}/.docker"
  become: no  
  tags:    
    - docker
    - update-postgres-image
