---
- name: Build Database Image
  hosts: "{{ target_hosts }}"
  become: "{{ ansible_become }}"
  tasks:
    - name: Build PostgreSQL container image
      ansible.builtin.include_role:
        name: docker
        tasks_from: build/database
      tags: [docker, build-database]
